fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

portail_user_inscription:
    path: /register
    defaults: { _controller: PortailUserBundle:Registration:register }
    methods:  ['GET','POST']

portail_user_connexion:
    path: /login
    defaults: { _controller: PortailUserBundle:Login:login }
    methods:  ['GET','POST']

portail_user_profile_show:
    path: /profile/
    defaults: { _controller: PortailUserBundle:Profile:show }
    methods:  ['GET','POST']

portail_user_profile_edit:
    path: /profile/edit
    defaults: { _controller: PortailUserBundle:Profile:edit }
    methods:  ['GET','POST']

portail_user_resetting_request:
    path: /request
    defaults: { _controller: PortailUserBundle:Resetting:request }
    methods:  ['GET','POST']

portail_user_resetting_send_email:
    path: /send-email
    defaults: { _controller: PortailUserBundle:Resetting:sendEmail }
    methods:  ['GET','POST']


portail_user_resetting_check_email:
    path: /resetting/check-email
    defaults: { _controller: PortailUserBundle:Resetting:checkEmail }
    methods:  ['GET','POST']


portail_user_confirmed:
    path: /confirmed
    defaults: { _controller: PortailUserBundle:Registration:confirmed }
    methods:  ['GET','POST']

portail_user_profile_observations:
    path: /profile/observations
    defaults: { _controller: PortailUserBundle:Observations:observations }
    methods:  ['GET','POST']

portail_user_profile_validations:
    path: /profile/validations/{id}/{valide}/{rejet}
    defaults: 
        _controller: PortailUserBundle:Observations:validations
        id: null
        valide: null
        rejet: null
    methods:  ['GET','POST']

portail_user_change_password:
    path: /change-password
    defaults: { _controller: PortailUserBundle:ChangePassword:changePassword }
    methods:  ['GET','POST']