fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

portail_user_inscription:
    path: /register
    defaults: { _controller: PortailUserBundle:Registration:register }
    methods:  ['GET','POST']

portail_user_connexion:
    path: /login
    defaults: { _controller: PortailUserBundle:Login:login }
    methods:  ['GET','POST']

portail_user_profile_show:
    path: /profile/
    defaults: { _controller: PortailUserBundle:Profile:show }
    methods:  ['GET','POST']

portail_user_profile_edit:
    path: /profile/edit
    defaults: { _controller: PortailUserBundle:Profile:edit }
    methods:  ['GET','POST']

portail_user_confirmed:
    path: /confirmed
    defaults: { _controller: PortailUserBundle:Registration:confirmed }
    methods:  ['GET','POST']

portail_user_profile_observations:
    path: /profile/observations
    defaults: { _controller: PortailUserBundle:Observations:observations }
    methods:  ['GET','POST']

portail_user_profile_validations:
    path: /profile/validations/{id}/{valide}/{rejet}
    defaults: 
        _controller: PortailUserBundle:Observations:validations
        id: null
        valide: null
        rejet: null
    methods:  ['GET','POST']