portail_user_homepage:
    path:     /
    defaults: { _controller: PortailUserBundle:Default:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


portail_user_inscription:
    path:     /inscription
    defaults: { _controller: PortailUserBundle:User:inscription }