imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    translator:      { fallbacks: ["%locale%"] }
    dossier_photos: '%kernel.root_dir%/../web/uploads/photos'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        root_path: %kernel.root_dir%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  spool:     { type: memory }
  transport: smtp
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    translator:      { fallbacks: ["%locale%"] }
    dossier_photos: '%kernel.root_dir%/../web/uploads/photos'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        root_path: %kernel.root_dir%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  spool:     { type: memory }
  transport: smtp
  host:      smtp.mailtrap.io
  username:  0575fda8e40871
  password:  1a7d8f7218350b
  auth_mode: cram-md5
  port: 2525

assetic:
  debug:          '%kernel.debug%'
  use_controller: '%kernel.debug%'
  filters:
    cssrewrite: ~
    jsqueeze:   ~
    scssphp:
      formatter: 'Leafo\ScssPhp\Formatter\Compressed'

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: Portail\UserBundle\Entity\User
    profile:
            form:
                type: Portail\UserBundle\Form\Type\ProfileFormType
    registration:
            form:
                type: Portail\UserBundle\Form\RegistrationType
                # if you are using Symfony < 2.8 you should use the type name instead
                # type: app_user_registration
    resetting:
                email:
                    from_email:
                        address:        resetting@example.com
                        sender_name:    Demo Resetting


easy_admin:
    site_name: '<strong>NAO - Administration</strong>'
    design:
        menu:
            - { label: 'Retour Site', route: 'portail_web_homepage' }
        # this is the only color you can change for the quick visual customization
        brand_color: '#6db941'
        color_scheme: 'light'
    entities:
        User:
            class: Portail\UserBundle\Entity\User
            list:
                fields: [{property: 'username', label: "Nom d'utilisateur"},{property: 'name', label:'Prénom'}, {property: 'surname', label: 'Nom'}, 'email', {property: 'enabled', label:'Activé'},'roles']
            form:
                fields:
                    - {property: 'username', label: "Nom d'utilisateur"}
                    - {property: 'name', label:'Prénom'}
                    - {property: 'surname', label: 'Nom'}
                    - email
                    - {property: 'city', label: 'Ville'}
                    - {property: 'job', label: 'Profession'}
                    - {property: 'enabled', label:'Activé'}
                    - {property: 'conditionUtilisation', label:"Conditions d'utilisation"}
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', label:'Mot de passe', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_UTILISATEUR': 'ROLE_USER','ROLE_MODERATEUR':'ROLE_MODERATEUR','ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN' } } }
