portail_web:
    resource: "@PortailWebBundle/Resources/config/routing.yml"
    prefix:   /

portail_user:
    resource: "@PortailUserBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"