portail_user:
    resource: "@PortailUserBundle/Resources/config/routing.yml"

portail_web:
    resource: "@PortailWebBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
