# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    portail.file_uploader:
        class: Portail\WebBundle\FileUploader\FileUploader
        arguments: ["%dossier_photos%"]
