# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    portail.file_uploader:
        class: Portail\WebBundle\FileUploader\FileUploader
        arguments: ["%dossier_photos%"]

    user.form.registration:
        class: Portail\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: user_user_registration }

    user.profile.form.type:
        class: Portail\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: portail_user_profile }

    fos_user.resetting.form.factory:
        class: FOS\UserBundle\Form\Factory\FormFactory
        arguments: ['@form.factory', '%fos_user.resetting.form.name%', '%fos_user.resetting.form.type%', '%fos_user.resetting.form.validation_groups%']

    user.resetting.form.type:
        class: Portail\UserBundle\Form\Type\ResettingFormType
        tags:
            - { name: form.type, alias: portail_user_resetting }
        arguments: ['%fos_user.model.user.class%']

    fos_user.listener.resetting:
        class: FOS\UserBundle\EventListener\ResettingListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: ['@router', '%fos_user.resetting.token_ttl%']

    fos_user.change_password.form.factory:
        class: FOS\UserBundle\Form\Factory\FormFactory
        arguments: ['@form.factory', '%fos_user.change_password.form.name%', '%fos_user.change_password.form.type%', '%fos_user.change_password.form.validation_groups%']

    fos_user.change_password.form.type:
        class: FOS\UserBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: portail_user_change_password }
        arguments: ['%fos_user.model.user.class%']

