<?php

namespace Portail\WebBundle\Repository;

/**
 * ObservationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationsRepository extends \Doctrine\ORM\EntityRepository
{
	public function observationsEnAttente() {
		$qb = $this->createQueryBuilder('c')
		   ->where('c.etat = 1');

		$query = $qb->getQuery();

		$result = $query->getResult();

		return $result;
	}
}
