<?php

namespace Portail\WebBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * OiseauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OiseauxRepository extends \Doctrine\ORM\EntityRepository
{
	public function oiseauChoisi($oiseauNomFr, $oiseauNomLat) {
		$qb = $this->createQueryBuilder('c')
		   ->where('c.nomFr = :oiseauNomFr')
		   ->andWhere('c.nomLa = :oiseauNomLat')
		   ->setParameters(array('oiseauNomFr' => $oiseauNomFr, 'oiseauNomLat' => $oiseauNomLat));

		$query = $qb->getQuery();

		$result = $query->getResult();

		return $result;
	}
}
