<?php

namespace Portail\WebBundle\Repository;

/**
 * OiseauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OiseauxRepository extends \Doctrine\ORM\EntityRepository
{
}
