<?php

namespace Portail\WebBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * OiseauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OiseauxRepository extends \Doctrine\ORM\EntityRepository
{
	public function oiseauChoisi($nomOiseau) {
		$qb = $this->createQueryBuilder('c')
		   ->where('c.nomFr = :nomOiseau')
		   ->setParameter('nomOiseau', $nomOiseau);

		$query = $qb->getQuery();

		$results = $query->getResult();

		return $results;
	}
}
