portail_web_homepage:
    path:     /
    defaults: { _controller: PortailWebBundle:Home:index }

portail_web_recherche:
    path:     /recherche
    defaults: { _controller: PortailWebBundle:Recherche:recherche }

portail_web_observation:
    path:     /observation
    defaults: { _controller: PortailWebBundle:Observation:observation }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


portail_user_inscription:
    path: /inscription
    defaults: { _controller: PortailUserBundle:Inscription:inscription }