portail_web_homepage:
    path:     /
    defaults: { _controller: PortailWebBundle:Home:index }

portail_web_recherche:
    path:     /recherche
    defaults: { _controller: PortailWebBundle:Recherche:recherche }

portail_web_observationStep1:
    path:     /observationStep1
    defaults: { _controller: PortailWebBundle:Observation:saisieOiseau }

portail_web_observationStep2:
    path:     /observationStep2-{nomFr}
    defaults: { _controller: PortailWebBundle:Observation:observation }

portail_web_ajax_autocomplete_recherche:
    path: /ajax/recherche/update/data
    defaults: { _controller: PortailWebBundle:AjaxAutocomplete:updateData }